-- ============================================================
-- Quartieri di Milano e comuni dell'area metropolitana.
-- Idempotente: aggiunge i mancanti e aggiorna la descrizione degli esistenti.
-- Il municipio è indicato solo dove è certo; l'amministratore può correggere
-- o aggiungere voci dal pannello di amministrazione.
-- ============================================================

INSERT INTO quartiere (nome, descrizione, municipio) VALUES
('Abbiategrasso','Quartiere di Milano.',5),
('Adriano','Quartiere di Milano.',2),
('Affori','Quartiere di Milano.',9),
('Arese','Comune dell''area metropolitana di Milano.',NULL),
('Assago','Comune dell''area metropolitana di Milano.',NULL),
('Baggio','Quartiere di Milano.',7),
('Bande Nere','Quartiere di Milano.',6),
('Baranzate','Comune dell''area metropolitana di Milano.',NULL),
('Barona','Quartiere di Milano.',6),
('Basiglio','Comune dell''area metropolitana di Milano.',NULL),
('Basmetto','Quartiere di Milano.',5),
('Bicocca','Quartiere di Milano.',9),
('Bollate','Comune dell''area metropolitana di Milano.',NULL),
('Bovisa','Quartiere di Milano.',9),
('Bovisasca','Quartiere di Milano.',9),
('Brera','Quartiere di Milano.',1),
('Bresso','Comune dell''area metropolitana di Milano.',NULL),
('Bruzzano','Quartiere di Milano.',9),
('Buccinasco','Comune dell''area metropolitana di Milano.',NULL),
('Buenos Aires','Quartiere di Milano.',3),
('Ca'' Granda','Quartiere di Milano.',9),
('Cadorna','Zona di Milano.',NULL),
('Cagnola','Quartiere di Milano.',8),
('Calvairate','Quartiere di Milano.',4),
('Cascina Merlata','Quartiere di Milano.',8),
('Centrale','Quartiere di Milano.',2),
('Centro Storico','Quartiere di Milano.',1),
('Cernusco sul Naviglio','Comune dell''area metropolitana di Milano.',NULL),
('Certosa','Quartiere di Milano.',8),
('Cesano Boldone','Comune dell''area metropolitana di Milano.',NULL),
('Chiaravalle','Quartiere di Milano.',5),
('Chiesa Rossa','Quartiere di Milano.',5),
('Cimiano','Quartiere di Milano.',3),
('Cinisello Balsamo','Comune dell''area metropolitana di Milano.',NULL),
('Città Studi','Quartiere di Milano.',3),
('CityLife','Quartiere di Milano.',8),
('Cologno Monzese','Comune dell''area metropolitana di Milano.',NULL),
('Comasina','Quartiere di Milano.',9),
('Cormano','Comune dell''area metropolitana di Milano.',NULL),
('Corsico','Comune dell''area metropolitana di Milano.',NULL),
('Corvetto','Quartiere di Milano.',4),
('Crescenzago','Quartiere di Milano.',2),
('Cusago','Comune dell''area metropolitana di Milano.',NULL),
('Cusano Milanino','Comune dell''area metropolitana di Milano.',NULL),
('Dergano','Quartiere di Milano.',9),
('Fiera','Quartiere di Milano.',8),
('Figino','Quartiere di Milano.',7),
('Forlanini','Quartiere di Milano.',4),
('Forze Armate','Quartiere di Milano.',7),
('Gaggiano','Comune dell''area metropolitana di Milano.',NULL),
('Gallaratese','Quartiere di Milano.',8),
('Gambara','Quartiere di Milano.',7),
('Giambellino','Quartiere di Milano.',6),
('Gioia','Zona di Milano.',NULL),
('Gorla','Quartiere di Milano.',2),
('Gratosoglio','Quartiere di Milano.',5),
('Greco','Quartiere di Milano.',2),
('Inganni','Quartiere di Milano.',7),
('Isola','Quartiere di Milano.',9),
('Lainate','Comune dell''area metropolitana di Milano.',NULL),
('Lambrate','Quartiere di Milano.',3),
('Lampugnano','Quartiere di Milano.',8),
('Lima','Quartiere di Milano.',3),
('Lodi','Zona di Milano.',NULL),
('Lorenteggio','Quartiere di Milano.',6),
('Loreto','Quartiere di Milano.',2),
('Maciachini','Quartiere di Milano.',9),
('Magenta - San Vittore','Quartiere di Milano.',1),
('Maggiolina','Quartiere di Milano.',9),
('Missori','Zona di Milano.',NULL),
('Molise','Quartiere di Milano.',4),
('Monluè','Quartiere di Milano.',4),
('Monza','Comune dell''area metropolitana di Milano.',NULL),
('Morsenchio','Quartiere di Milano.',4),
('Moscova','Quartiere di Milano.',1),
('Muggiano','Quartiere di Milano.',6),
('Musocco','Quartiere di Milano.',8),
('Navigli','Quartiere di Milano.',6),
('Niguarda','Quartiere di Milano.',9),
('NoLo','Quartiere di Milano.',2),
('Novate Milanese','Comune dell''area metropolitana di Milano.',NULL),
('Opera','Comune dell''area metropolitana di Milano.',NULL),
('Ortica','Quartiere di Milano.',3),
('Ortomercato','Quartiere di Milano.',4),
('Paderno Dugnano','Comune dell''area metropolitana di Milano.',NULL),
('Padova','Quartiere di Milano.',2),
('Pasteur','Quartiere di Milano.',2),
('Pero','Comune dell''area metropolitana di Milano.',NULL),
('Peschiera Borromeo','Comune dell''area metropolitana di Milano.',NULL),
('Piola','Quartiere di Milano.',3),
('Pioltello','Comune dell''area metropolitana di Milano.',NULL),
('Ponte Lambro','Quartiere di Milano.',4),
('Porta Garibaldi','Quartiere di Milano.',1),
('Porta Genova','Quartiere di Milano.',6),
('Porta Nuova','Zona di Milano.',NULL),
('Porta Romana','Quartiere di Milano.',4),
('Porta Venezia','Quartiere di Milano.',1),
('Porta Vittoria','Quartiere di Milano.',4),
('Portello','Quartiere di Milano.',8),
('Pratocentenaro','Quartiere di Milano.',9),
('Precotto','Quartiere di Milano.',2),
('QT8','Quartiere di Milano.',8),
('Quarto Cagnino','Quartiere di Milano.',7),
('Quarto Oggiaro','Quartiere di Milano.',8),
('Quinto Romano','Quartiere di Milano.',7),
('Quintosole','Quartiere di Milano.',5),
('Rho','Comune dell''area metropolitana di Milano.',NULL),
('Ripamonti','Quartiere di Milano.',5),
('Rogoredo','Quartiere di Milano.',4),
('Roserio','Quartiere di Milano.',8),
('Rovereto','Quartiere di Milano.',2),
('Rozzano','Comune dell''area metropolitana di Milano.',NULL),
('Rubattino','Quartiere di Milano.',3),
('San Cristoforo','Quartiere di Milano.',6),
('San Donato Milanese','Comune dell''area metropolitana di Milano.',NULL),
('San Giuliano Milanese','Comune dell''area metropolitana di Milano.',NULL),
('San Siro','Quartiere di Milano.',7),
('Sant''Ambrogio','Quartiere di Milano.',1),
('Santa Giulia','Quartiere di Milano.',4),
('Segrate','Comune dell''area metropolitana di Milano.',NULL),
('Selinunte','Quartiere di Milano.',7),
('Selvanesco','Quartiere di Milano.',5),
('Sempione','Quartiere di Milano.',8),
('Sesto San Giovanni','Comune dell''area metropolitana di Milano.',NULL),
('Settimo Milanese','Comune dell''area metropolitana di Milano.',NULL),
('Solari','Quartiere di Milano.',6),
('Stadera','Quartiere di Milano.',5),
('Taliedo','Quartiere di Milano.',4),
('Ticinese','Zona di Milano.',NULL),
('Tortona','Quartiere di Milano.',6),
('Trenno','Quartiere di Milano.',8),
('Trezzano sul Naviglio','Comune dell''area metropolitana di Milano.',NULL),
('Turro','Quartiere di Milano.',2),
('Vigentino','Quartiere di Milano.',5),
('Villapizzone','Quartiere di Milano.',8),
('Vimodrone','Comune dell''area metropolitana di Milano.',NULL),
('Washington','Quartiere di Milano.',6),
('Zara','Quartiere di Milano.',9),
('Zibido San Giacomo','Comune dell''area metropolitana di Milano.',NULL)
AS nuovo ON DUPLICATE KEY UPDATE
  descrizione = IF(quartiere.descrizione IS NULL OR quartiere.descrizione = '', nuovo.descrizione, quartiere.descrizione),
  municipio = COALESCE(quartiere.municipio, nuovo.municipio);
